CREATE TABLE CONFIG(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LIBELLE VARCHAR(255) NOT NULL,
    VALEUR VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE ROLE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LIBELLE VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE UTILISATEUR(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(50) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    ID_ROLE INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE ACTIVITE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(50) NOT NULL,
    LIEU VARCHAR(50) NOT NULL,
    SHORT_DESCRIPTION TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    ID_UTILISATEUR INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE COMMENTAIRE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TEXTE TEXT NOT NULL,
    ID_ACTIVITE INT NOT NULL,
    ID_UTILISATEUR INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE PHOTO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CHEMIN VARCHAR(255) NOT NULL,
    ID_ACTIVITE INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE UTILISATEUR ADD CONSTRAINT FK_UTILISATEUR_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID);
ALTER TABLE ACTIVITE ADD CONSTRAINT FK_ACTIVITE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID);
ALTER TABLE COMMENTAIRE ADD CONSTRAINT FK_COMMENTAIRE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID);
ALTER TABLE COMMENTAIRE ADD CONSTRAINT FK_COMMENTAIRE_ACTIVITE FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE(ID);
ALTER TABLE PHOTO ADD CONSTRAINT FK_PHOTO_ACTIVITE FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE(ID);