CREATE TABLE CONFIG(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LIBELLE VARCHAR(255)
    VALEUR VARCHAR(255)
);

CREATE TABLE ROLE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LIBELLE VARCHAR(50)
);

CREATE TABLE UTILISATEUR(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    LOGIN VARCHAR(50),
    PASSWORD VARCHAR(60),
    ID_ROLE INT
);

CREATE TABLE ACTIVITE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(50),
    LIEU VARCHAR(50),
    SHORT_DESCRIPTION VARCHAR(50),
    DESCRIPTION VARCHAR(50),
    ID_UTILISATEUR INT
);

CREATE TABLE COMMENTAIRE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TEXTE TEXT,
    ID_ACTIVITE INT,
    ID_UTILISATEUR INT
);

CREATE TABLE PHOTO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CHEMIN VARCHAR(255),
    ID_ACTIVITE INT
);

ALTER TABLE UTILISATEUR ADD CONSTRAINT FK_UTILISATEUR_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID);
ALTER TABLE ACTIVITE ADD CONSTRAINT FK_ACTIVITE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID);
ALTER TABLE COMMENTAIRE ADD CONSTRAINT FK_COMMENTAIRE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID);
ALTER TABLE COMMENTAIRE ADD CONSTRAINT FK_COMMENTAIRE_ACTIVITE FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE(ID);
ALTER TABLE PHOTO ADD CONSTRAINT FK_PHOTO_ACTIVITE FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE(ID);